export default {
  arr: [
    'Resume Pablo de Jesús',
    'Full Stack Developer',
    'Career Summary',
    'Software engineer with more of two years of experience in the backend part and frontend using PHP technology and its Codeigniter and Yii2 frameworks. Participating in information management projects in databases. I am willing to learn more and use other technologies especially in JavaScript, Python and Ruby.',
    'Work Experience',
    'Full Stack Developer',
    'September 2018 - December 2018',
    "Responsible for full stack development and database of the module 'didactic instrumentation' for use by all teachers of the National Technological Institute  of Mexico.",
    "Achievements:",
    'Before the teachers made the didactic instrumentation in programs such as "word", following specific standards and formats, but now:',
    "Filling data is fast, intuitive and effective.",
    "At the end of the capture the teachers obtain the didactic instrumentation in a PDF complying with the norms and formats required and the confidence that everything they wrote and saved is in a database.",
    "The document once generated can be consulted or edited on the platform when and where they want from a web browser and with an internet connection.",
    "Technologies used:",
    "Web Developer",
    "February 2018 - July 2018",
    "Responsible for full stack development and database of platform for the management of laundry process in the company 'Lavados Especiales' from Puebla city.",
    "Description",
    "Platform for automate in efficiently way the control of laundry processes and the company administration with the implementation of the project to obtain a better fastest and internal control.",
    "Skills and Tools",
    "Languajes",
    "Others",
    "Education",
    "Computer Systems Enginer",
    "Awards",
    "State programming competition",
    'In the',
    "Language",
    "Spanish",
    "Native",
    "English",
    "Intermediate",
    "Interests",
    "Reading",
    "Swimming",
    "Watching movies",
    "Volunteer",
    "Full Time Missioner",
    "April 2011 - September 2013",
    "National Student Event of Technological Innovation (ENEIT) 2016",
    'National stage in the IT of Pachuca from 22 to 25 November 2016 by the project "Enerluz".',
    'Certifications',
    'Regional stage in IT of Gustavo A. Madero in Mexico City, from 20 to 23 September 2016 by the projects “Enerluz” and "Autosilla”. Winner with “Enerluz” project.',
    'Full Stack Developer',
    'Grupo Salinas',
    'March 2019 - June 2020',
    'Java, Vue.js and Python full stack developer in the company.',
    'Responsible for developing REST services and web portals for the management of the company.',
    'on April 22, 2016. Winner of the third place in the intermediate category.',
    //Alphacredit
    'Alphacredit',
    'Julio 2020 - At present',
    'Java and .Net Core developer in the company.',
    'Responsible for developing Java and .Net Core processes in the company.',
  ]
}