export default {
  arr: [
    'Curriculum Vitae Pablo de Jesús',
    'Desarrollador Full Stack',
    'Resúmen',
    'Ingeniero de software con dos años de experiencia en la parte de backend y frontend utilizando la tecnología PHP y sus frameworks Codeigniter y Yii2. Participando en proyectos de gestión de información en bases de datos. Estoy dispuesto a aprender más y usar otras tecnologías sobre todo en JavaScript, Python y Ruby.',
    'Experiencia Laboral',
    'Desarrollador Full Stack',
    'Septiembre de 2018 - Diciembre de 2018',
    "Responsable del desarrollo full stack y la base de datos del módulo 'Instrumentación didáctica' para uso de todos los docentes del Tecnológico Nacional de México.",
    "Logros:",
    'Antes los docentes hacían la instrumentación didáctica en programas como "word", siguiendo normas y formatos específicos, pero ahora:',
    "El llenado de datos es rápido, intuitivo y eficaz.",
    "Al final de la captura los docentes obtienen la instrumentación didáctica en un PDF cumpliendo las normas y formatos requeridos y la confianza de que todo lo que escribieron y guardaron se encuentra en una base de datos.",
    "El documento una vez generado puede ser consultado o editado en la plataforma cuando y donde ellos quieran desde un navegador web y con una conexión a internet.",
    "Tecnologías usadas:",
    "Desarrollador Web",
    "Febero de 2018 - Julio de 2018",
    "Responsable del desarrollo full stack y de base de datos de la plataforma para la gestión del proceso de lavandería en la empresa 'Lavados Especiales' en la ciudad de Puebla.",
    "Descripción",
    "Plataforma para automatizar de manera eficiente el control de los procesos de lavado y la administración de la empresa con la implementación del proyecto para obtener un mejor control interno más rápido y eficaz.",
    "Habilidades y Herramientas",
    "Lenguajes",
    "Otros",
    "Educación",
    "Ingeniería en Sistemas Computacionales",
    "Reconocimientos",
    "Concurso estatal de programación",
    'En el',
    "Idiomas",
    "Español",
    "Nativo",
    "Inglés",
    "Intermedio",
    "Intereses",
    "Leer",
    "Nadar",
    "Ver películas",
    "Voluntariado",
    "Misionero de Tiempo Completo",
    "Abril de 2011 - Septiembre de 2013",
    "Evento Nacional Estudiantil de Innovación Tecnológica (ENEIT) 2016",
    'Etapa nacional en el IT de Pachuca del 22 al 25 de noviembre de 2016 por el proyecto “Enerluz".',
    'Certificaciones',
    'Etapa regional en el IT de Gustavo A. Madero en la Ciudad de México, del 20 al 23 de septiembre de 2016 por los proyectos “Enerluz” y “Autosilla”. Ganador con “Enerluz”.',
    'Desarrollador Full Stack',
    'Grupo Salinas',
    'Marzo 2019 - actualmente',
    'Desarrollador full stack en Java en la empresa.',
    'Responsable de desarrollar servicios REST y portales web para la gestión de la empresa.',
    'el 22 de Abril de 2016. Ganador del tercer lugar en la categoría intermedia.'
  ]
}